let countries = [
  {
    code: 'AF',
    dial_code: '+93',
    flag: '🇦🇫',
    name: 'Afghanistan',
    label: '🇦🇫 +93',
    value: '+93',
  },
  {
    code: 'AX',
    dial_code: '+358',
    flag: '🇦🇽',
    name: 'Åland Islands',
    label: '🇦🇽 +358',
    value: '+358',
  },
  {
    code: 'AL',
    dial_code: '+355',
    flag: '🇦🇱',
    name: 'Albania',
    label: '🇦🇱 +355',
    value: '+355',
  },
  {
    code: 'DZ',
    dial_code: '+213',
    flag: '🇩🇿',
    name: 'Algeria',
    label: '🇩🇿 +213',
    value: '+213',
  },
  {
    code: 'AS',
    dial_code: '+1684',
    flag: '🇦🇸',
    name: 'American Samoa',
    label: '🇦🇸 +1684',
    value: '+1684',
  },
  {
    code: 'AD',
    dial_code: '+376',
    flag: '🇦🇩',
    name: 'Andorra',
    label: '🇦🇩 +376',
    value: '+376',
  },
  {
    code: 'AO',
    dial_code: '+244',
    flag: '🇦🇴',
    name: 'Angola',
    label: '🇦🇴 +244',
    value: '+244',
  },
  {
    code: 'AI',
    dial_code: '+1264',
    flag: '🇦🇮',
    name: 'Anguilla',
    label: '🇦🇮 +1264',
    value: '+1264',
  },
  {
    code: 'AQ',
    dial_code: '+672',
    flag: '🇦🇶',
    name: 'Antarctica',
    label: '🇦🇶 +672',
    value: '+672',
  },
  {
    code: 'AG',
    dial_code: '+1268',
    flag: '🇦🇬',
    name: 'Antigua and Barbuda',
    label: '🇦🇬 +1268',
    value: '+1268',
  },
  {
    code: 'AR',
    dial_code: '+54',
    flag: '🇦🇷',
    name: 'Argentina',
    label: '🇦🇷 +54',
    value: '+54',
  },
  {
    code: 'AM',
    dial_code: '+374',
    flag: '🇦🇲',
    name: 'Armenia',
    label: '🇦🇲 +374',
    value: '+374',
  },
  {
    code: 'AW',
    dial_code: '+297',
    flag: '🇦🇼',
    name: 'Aruba',
    label: '🇦🇼 +297',
    value: '+297',
  },
  {
    code: 'AU',
    dial_code: '+61',
    flag: '🇦🇺',
    name: 'Australia',
    label: '🇦🇺 +61',
    value: '+61',
  },
  {
    code: 'AT',
    dial_code: '+43',
    flag: '🇦🇹',
    name: 'Austria',
    label: '🇦🇹 +43',
    value: '+43',
  },
  {
    code: 'AZ',
    dial_code: '+994',
    flag: '🇦🇿',
    name: 'Azerbaijan',
    label: '🇦🇿 +994',
    value: '+994',
  },
  {
    code: 'BS',
    dial_code: '+1242',
    flag: '🇧🇸',
    name: 'Bahamas',
    label: '🇧🇸 +1242',
    value: '+1242',
  },
  {
    code: 'BH',
    dial_code: '+973',
    flag: '🇧🇭',
    name: 'Bahrain',
    label: '🇧🇭 +973',
    value: '+973',
  },
  {
    code: 'BD',
    dial_code: '+880',
    flag: '🇧🇩',
    name: 'Bangladesh',
    label: '🇧🇩 +880',
    value: '+880',
  },
  {
    code: 'BB',
    dial_code: '+1246',
    flag: '🇧🇧',
    name: 'Barbados',
    label: '🇧🇧 +1246',
    value: '+1246',
  },
  {
    code: 'BY',
    dial_code: '+375',
    flag: '🇧🇾',
    name: 'Belarus',
    label: '🇧🇾 +375',
    value: '+375',
  },
  {
    code: 'BE',
    dial_code: '+32',
    flag: '🇧🇪',
    name: 'Belgium',
    label: '🇧🇪 +32',
    value: '+32',
  },
  {
    code: 'BZ',
    dial_code: '+501',
    flag: '🇧🇿',
    name: 'Belize',
    label: '🇧🇿 +501',
    value: '+501',
  },
  {
    code: 'BJ',
    dial_code: '+229',
    flag: '🇧🇯',
    name: 'Benin',
    label: '🇧🇯 +229',
    value: '+229',
  },
  {
    code: 'BM',
    dial_code: '+1441',
    flag: '🇧🇲',
    name: 'Bermuda',
    label: '🇧🇲 +1441',
    value: '+1441',
  },
  {
    code: 'BT',
    dial_code: '+975',
    flag: '🇧🇹',
    name: 'Bhutan',
    label: '🇧🇹 +975',
    value: '+975',
  },
  {
    code: 'BO',
    dial_code: '+591',
    flag: '🇧🇴',
    name: 'Bolivia, Plurinational State of bolivia',
    label: '🇧🇴 +591',
    value: '+591',
  },
  {
    code: 'BA',
    dial_code: '+387',
    flag: '🇧🇦',
    name: 'Bosnia and Herzegovina',
    label: '🇧🇦 +387',
    value: '+387',
  },
  {
    code: 'BW',
    dial_code: '+267',
    flag: '🇧🇼',
    name: 'Botswana',
    label: '🇧🇼 +267',
    value: '+267',
  },
  {
    code: 'BV',
    dial_code: '+47',
    flag: '🏳',
    name: 'Bouvet Island',
    label: '🏳 +47',
    value: '+47',
  },
  {
    code: 'BR',
    dial_code: '+55',
    flag: '🇧🇷',
    name: 'Brazil',
    label: '🇧🇷 +55',
    value: '+55',
  },
  {
    code: 'IO',
    dial_code: '+246',
    flag: '🇮🇴',
    name: 'British Indian Ocean Territory',
    label: '🇮🇴 +246',
    value: '+246',
  },
  {
    code: 'BN',
    dial_code: '+673',
    flag: '🇧🇳',
    name: 'Brunei Darussalam',
    label: '🇧🇳 +673',
    value: '+673',
  },
  {
    code: 'BG',
    dial_code: '+359',
    flag: '🇧🇬',
    name: 'Bulgaria',
    label: '🇧🇬 +359',
    value: '+359',
  },
  {
    code: 'BF',
    dial_code: '+226',
    flag: '🇧🇫',
    name: 'Burkina Faso',
    label: '🇧🇫 +226',
    value: '+226',
  },
  {
    code: 'BI',
    dial_code: '+257',
    flag: '🇧🇮',
    name: 'Burundi',
    label: '🇧🇮 +257',
    value: '+257',
  },
  {
    code: 'KH',
    dial_code: '+855',
    flag: '🇰🇭',
    name: 'Cambodia',
    label: '🇰🇭 +855',
    value: '+855',
  },
  {
    code: 'CM',
    dial_code: '+237',
    flag: '🇨🇲',
    name: 'Cameroon',
    label: '🇨🇲 +237',
    value: '+237',
  },
  {
    code: 'CA',
    dial_code: '+1',
    flag: '🇨🇦',
    name: 'Canada',
    label: '🇨🇦 +1',
    value: '+1',
  },
  {
    code: 'CV',
    dial_code: '+238',
    flag: '🇨🇻',
    name: 'Cape Verde',
    label: '🇨🇻 +238',
    value: '+238',
  },
  {
    code: 'KY',
    dial_code: '+ 345',
    flag: '🇰🇾',
    name: 'Cayman Islands',
    label: '🇰🇾 + 345',
    value: '+ 345',
  },
  {
    code: 'CF',
    dial_code: '+236',
    flag: '🇨🇫',
    name: 'Central African Republic',
    label: '🇨🇫 +236',
    value: '+236',
  },
  {
    code: 'TD',
    dial_code: '+235',
    flag: '🇹🇩',
    name: 'Chad',
    label: '🇹🇩 +235',
    value: '+235',
  },
  {
    code: 'CL',
    dial_code: '+56',
    flag: '🇨🇱',
    name: 'Chile',
    label: '🇨🇱 +56',
    value: '+56',
  },
  {
    code: 'CN',
    dial_code: '+86',
    flag: '🇨🇳',
    name: 'China',
    label: '🇨🇳 +86',
    value: '+86',
  },
  {
    code: 'CX',
    dial_code: '+61',
    flag: '🇨🇽',
    name: 'Christmas Island',
    label: '🇨🇽 +61',
    value: '+61',
  },
  {
    code: 'CC',
    dial_code: '+61',
    flag: '🇨🇨',
    name: 'Cocos (Keeling) Islands',
    label: '🇨🇨 +61',
    value: '+61',
  },
  {
    code: 'CO',
    dial_code: '+57',
    flag: '🇨🇴',
    name: 'Colombia',
    label: '🇨🇴 +57',
    value: '+57',
  },
  {
    code: 'KM',
    dial_code: '+269',
    flag: '🇰🇲',
    name: 'Comoros',
    label: '🇰🇲 +269',
    value: '+269',
  },
  {
    code: 'CG',
    dial_code: '+242',
    flag: '🇨🇬',
    name: 'Congo',
    label: '🇨🇬 +242',
    value: '+242',
  },
  {
    code: 'CD',
    dial_code: '+243',
    flag: '🇨🇩',
    name: 'Congo, The Democratic Republic of the Congo',
    label: '🇨🇩 +243',
    value: '+243',
  },
  {
    code: 'CK',
    dial_code: '+682',
    flag: '🇨🇰',
    name: 'Cook Islands',
    label: '🇨🇰 +682',
    value: '+682',
  },
  {
    code: 'CR',
    dial_code: '+506',
    flag: '🇨🇷',
    name: 'Costa Rica',
    label: '🇨🇷 +506',
    value: '+506',
  },
  {
    code: 'CI',
    dial_code: '+225',
    flag: '🇨🇮',
    name: "Cote d'Ivoire",
    label: '🇨🇮 +225',
    value: '+225',
  },
  {
    code: 'HR',
    dial_code: '+385',
    flag: '🇭🇷',
    name: 'Croatia',
    label: '🇭🇷 +385',
    value: '+385',
  },
  {
    code: 'CU',
    dial_code: '+53',
    flag: '🇨🇺',
    name: 'Cuba',
    label: '🇨🇺 +53',
    value: '+53',
  },
  {
    code: 'CY',
    dial_code: '+357',
    flag: '🇨🇾',
    name: 'Cyprus',
    label: '🇨🇾 +357',
    value: '+357',
  },
  {
    code: 'CZ',
    dial_code: '+420',
    flag: '🇨🇿',
    name: 'Czech Republic',
    label: '🇨🇿 +420',
    value: '+420',
  },
  {
    code: 'DK',
    dial_code: '+45',
    flag: '🇩🇰',
    name: 'Denmark',
    label: '🇩🇰 +45',
    value: '+45',
  },
  {
    code: 'DJ',
    dial_code: '+253',
    flag: '🇩🇯',
    name: 'Djibouti',
    label: '🇩🇯 +253',
    value: '+253',
  },
  {
    code: 'DM',
    dial_code: '+1767',
    flag: '🇩🇲',
    name: 'Dominica',
    label: '🇩🇲 +1767',
    value: '+1767',
  },
  {
    code: 'DO',
    dial_code: '+1849',
    flag: '🇨🇩',
    name: 'Dominican Republic',
    label: '🇨🇩 +1849',
    value: '+1849',
  },
  {
    code: 'EC',
    dial_code: '+593',
    flag: '🇪🇨',
    name: 'Ecuador',
    label: '🇪🇨 +593',
    value: '+593',
  },
  {
    code: 'EG',
    dial_code: '+20',
    flag: '🇪🇬',
    name: 'Egypt',
    label: '🇪🇬 +20',
    value: '+20',
  },
  {
    code: 'SV',
    dial_code: '+503',
    flag: '🇸🇻',
    name: 'El Salvador',
    label: '🇸🇻 +503',
    value: '+503',
  },
  {
    code: 'GQ',
    dial_code: '+240',
    flag: '🇬🇶',
    name: 'Equatorial Guinea',
    label: '🇬🇶 +240',
    value: '+240',
  },
  {
    code: 'ER',
    dial_code: '+291',
    flag: '🇪🇷',
    name: 'Eritrea',
    label: '🇪🇷 +291',
    value: '+291',
  },
  {
    code: 'EE',
    dial_code: '+372',
    flag: '🇪🇪',
    name: 'Estonia',
    label: '🇪🇪 +372',
    value: '+372',
  },
  {
    code: 'ET',
    dial_code: '+251',
    flag: '🇪🇹',
    name: 'Ethiopia',
    label: '🇪🇹 +251',
    value: '+251',
  },
  {
    code: 'FK',
    dial_code: '+500',
    flag: '🇫🇰',
    name: 'Falkland Islands (Malvinas)',
    label: '🇫🇰 +500',
    value: '+500',
  },
  {
    code: 'FO',
    dial_code: '+298',
    flag: '🇫🇴',
    name: 'Faroe Islands',
    label: '🇫🇴 +298',
    value: '+298',
  },
  {
    code: 'FJ',
    dial_code: '+679',
    flag: '🇫🇯',
    name: 'Fiji',
    label: '🇫🇯 +679',
    value: '+679',
  },
  {
    code: 'FI',
    dial_code: '+358',
    flag: '🇫🇮',
    name: 'Finland',
    label: '🇫🇮 +358',
    value: '+358',
  },
  {
    code: 'FR',
    dial_code: '+33',
    flag: '🇫🇷',
    name: 'France',
    label: '🇫🇷 +33',
    value: '+33',
  },
  {
    code: 'GF',
    dial_code: '+594',
    flag: '🇬🇫',
    name: 'French Guiana',
    label: '🇬🇫 +594',
    value: '+594',
  },
  {
    code: 'PF',
    dial_code: '+689',
    flag: '🇵🇫',
    name: 'French Polynesia',
    label: '🇵🇫 +689',
    value: '+689',
  },
  {
    code: 'TF',
    dial_code: '+262',
    flag: '🇹🇫',
    name: 'French Southern Territories',
    label: '🇹🇫 +262',
    value: '+262',
  },
  {
    code: 'GA',
    dial_code: '+241',
    flag: '🇬🇦',
    name: 'Gabon',
    label: '🇬🇦 +241',
    value: '+241',
  },
  {
    code: 'GM',
    dial_code: '+220',
    flag: '🇬🇲',
    name: 'Gambia',
    label: '🇬🇲 +220',
    value: '+220',
  },
  {
    code: 'GE',
    dial_code: '+995',
    flag: '🇬🇪',
    name: 'Georgia',
    label: '🇬🇪 +995',
    value: '+995',
  },
  {
    code: 'DE',
    dial_code: '+49',
    flag: '🇩🇪',
    name: 'Germany',
    label: '🇩🇪 +49',
    value: '+49',
  },
  {
    code: 'GH',
    dial_code: '+233',
    flag: '🇬🇭',
    name: 'Ghana',
    label: '🇬🇭 +233',
    value: '+233',
  },
  {
    code: 'GI',
    dial_code: '+350',
    flag: '🇬🇮',
    name: 'Gibraltar',
    label: '🇬🇮 +350',
    value: '+350',
  },
  {
    code: 'GR',
    dial_code: '+30',
    flag: '🇬🇷',
    name: 'Greece',
    label: '🇬🇷 +30',
    value: '+30',
  },
  {
    code: 'GL',
    dial_code: '+299',
    flag: '🇬🇱',
    name: 'Greenland',
    label: '🇬🇱 +299',
    value: '+299',
  },
  {
    code: 'GD',
    dial_code: '+1473',
    flag: '🇬🇩',
    name: 'Grenada',
    label: '🇬🇩 +1473',
    value: '+1473',
  },
  {
    code: 'GP',
    dial_code: '+590',
    flag: '🇬🇵',
    name: 'Guadeloupe',
    label: '🇬🇵 +590',
    value: '+590',
  },
  {
    code: 'GU',
    dial_code: '+1671',
    flag: '🇬🇺',
    name: 'Guam',
    label: '🇬🇺 +1671',
    value: '+1671',
  },
  {
    code: 'GT',
    dial_code: '+502',
    flag: '🇬🇹',
    name: 'Guatemala',
    label: '🇬🇹 +502',
    value: '+502',
  },
  {
    code: 'GG',
    dial_code: '+44',
    flag: '🇬🇬',
    name: 'Guernsey',
    label: '🇬🇬 +44',
    value: '+44',
  },
  {
    code: 'GN',
    dial_code: '+224',
    flag: '🇬🇳',
    name: 'Guinea',
    label: '🇬🇳 +224',
    value: '+224',
  },
  {
    code: 'GW',
    dial_code: '+245',
    flag: '🇬🇼',
    name: 'Guinea-Bissau',
    label: '🇬🇼 +245',
    value: '+245',
  },
  {
    code: 'GY',
    dial_code: '+592',
    flag: '🇬🇾',
    name: 'Guyana',
    label: '🇬🇾 +592',
    value: '+592',
  },
  {
    code: 'HT',
    dial_code: '+509',
    flag: '🇭🇹',
    name: 'Haiti',
    label: '🇭🇹 +509',
    value: '+509',
  },
  {
    code: 'HM',
    dial_code: '+0',
    flag: '🏳',
    name: 'Heard Island and Mcdonald Islands',
    label: '🏳 +0',
    value: '+0',
  },
  {
    code: 'VA',
    dial_code: '+379',
    flag: '🇻🇦',
    name: 'Holy See (Vatican City State)',
    label: '🇻🇦 +379',
    value: '+379',
  },
  {
    code: 'HN',
    dial_code: '+504',
    flag: '🇭🇳',
    name: 'Honduras',
    label: '🇭🇳 +504',
    value: '+504',
  },
  {
    code: 'HK',
    dial_code: '+852',
    flag: '🇭🇰',
    name: 'Hong Kong',
    label: '🇭🇰 +852',
    value: '+852',
  },
  {
    code: 'HU',
    dial_code: '+36',
    flag: '🇭🇺',
    name: 'Hungary',
    label: '🇭🇺 +36',
    value: '+36',
  },
  {
    code: 'IS',
    dial_code: '+354',
    flag: '🇮🇸',
    name: 'Iceland',
    label: '🇮🇸 +354',
    value: '+354',
  },
  {
    code: 'IN',
    dial_code: '+91',
    flag: '🇮🇳',
    name: 'India',
    label: '🇮🇳 +91',
    value: '+91',
  },
  {
    code: 'ID',
    dial_code: '+62',
    flag: '🇮🇩',
    name: 'Indonesia',
    label: '🇮🇩 +62',
    value: '+62',
  },
  {
    code: 'IR',
    dial_code: '+98',
    flag: '🇮🇷',
    name: 'Iran, Islamic Republic of Persian Gulf',
    label: '🇮🇷 +98',
    value: '+98',
  },
  {
    code: 'IQ',
    dial_code: '+964',
    flag: '�🇶',
    name: 'Iraq',
    label: '�🇶 +964',
    value: '+964',
  },
  {
    code: 'IE',
    dial_code: '+353',
    flag: '🇮🇪',
    name: 'Ireland',
    label: '🇮🇪 +353',
    value: '+353',
  },
  {
    code: 'IM',
    dial_code: '+44',
    flag: '🇮🇲',
    name: 'Isle of Man',
    label: '🇮🇲 +44',
    value: '+44',
  },
  {
    code: 'IL',
    dial_code: '+972',
    flag: '🇮🇱',
    name: 'Israel',
    label: '🇮🇱 +972',
    value: '+972',
  },
  {
    code: 'IT',
    dial_code: '+39',
    flag: '🇮🇹',
    name: 'Italy',
    label: '🇮🇹 +39',
    value: '+39',
  },
  {
    code: 'JM',
    dial_code: '+1876',
    flag: '🇯🇲',
    name: 'Jamaica',
    label: '🇯🇲 +1876',
    value: '+1876',
  },
  {
    code: 'JP',
    dial_code: '+81',
    flag: '🇯🇵',
    name: 'Japan',
    label: '🇯🇵 +81',
    value: '+81',
  },
  {
    code: 'JE',
    dial_code: '+44',
    flag: '🇯🇪',
    name: 'Jersey',
    label: '🇯🇪 +44',
    value: '+44',
  },
  {
    code: 'JO',
    dial_code: '+962',
    flag: '🇯🇴',
    name: 'Jordan',
    label: '🇯🇴 +962',
    value: '+962',
  },
  {
    code: 'KZ',
    dial_code: '+7',
    flag: '🇰🇿',
    name: 'Kazakhstan',
    label: '🇰🇿 +7',
    value: '+7',
  },
  {
    code: 'KE',
    dial_code: '+254',
    flag: '🇰🇪',
    name: 'Kenya',
    label: '🇰🇪 +254',
    value: '+254',
  },
  {
    code: 'KI',
    dial_code: '+686',
    flag: '🇰🇮',
    name: 'Kiribati',
    label: '🇰🇮 +686',
    value: '+686',
  },
  {
    code: 'KP',
    dial_code: '+850',
    flag: '🇰🇵',
    name: "Korea, Democratic People's Republic of Korea",
    label: '🇰🇵 +850',
    value: '+850',
  },
  {
    code: 'KR',
    dial_code: '+82',
    flag: '🇰🇷',
    name: 'Korea, Republic of South Korea',
    label: '🇰🇷 +82',
    value: '+82',
  },
  {
    code: 'XK',
    dial_code: '+383',
    flag: '🇽🇰',
    name: 'Kosovo',
    label: '🇽🇰 +383',
    value: '+383',
  },
  {
    code: 'KW',
    dial_code: '+965',
    flag: '🇰🇼',
    name: 'Kuwait',
    label: '🇰🇼 +965',
    value: '+965',
  },
  {
    code: 'KG',
    dial_code: '+996',
    flag: '🇰🇬',
    name: 'Kyrgyzstan',
    label: '🇰🇬 +996',
    value: '+996',
  },
  {
    code: 'LA',
    dial_code: '+856',
    flag: '🇱🇦',
    name: 'Laos',
    label: '🇱🇦 +856',
    value: '+856',
  },
  {
    code: 'LV',
    dial_code: '+371',
    flag: '🇱🇻',
    name: 'Latvia',
    label: '🇱🇻 +371',
    value: '+371',
  },
  {
    code: 'LB',
    dial_code: '+961',
    flag: '🇱🇧',
    name: 'Lebanon',
    label: '🇱🇧 +961',
    value: '+961',
  },
  {
    code: 'LS',
    dial_code: '+266',
    flag: '🇱🇸',
    name: 'Lesotho',
    label: '🇱🇸 +266',
    value: '+266',
  },
  {
    code: 'LR',
    dial_code: '+231',
    flag: '🇱🇷',
    name: 'Liberia',
    label: '🇱🇷 +231',
    value: '+231',
  },
  {
    code: 'LY',
    dial_code: '+218',
    flag: '🇱🇾',
    name: 'Libyan Arab Jamahiriya',
    label: '🇱🇾 +218',
    value: '+218',
  },
  {
    code: 'LI',
    dial_code: '+423',
    flag: '🇱🇮',
    name: 'Liechtenstein',
    label: '🇱🇮 +423',
    value: '+423',
  },
  {
    code: 'LT',
    dial_code: '+370',
    flag: '🇱🇹',
    name: 'Lithuania',
    label: '🇱🇹 +370',
    value: '+370',
  },
  {
    code: 'LU',
    dial_code: '+352',
    flag: '🇱🇺',
    name: 'Luxembourg',
    label: '🇱🇺 +352',
    value: '+352',
  },
  {
    code: 'MO',
    dial_code: '+853',
    flag: '🇲🇴',
    name: 'Macao',
    label: '🇲🇴 +853',
    value: '+853',
  },
  {
    code: 'MK',
    dial_code: '+389',
    flag: '🇲🇰',
    name: 'Macedonia',
    label: '🇲🇰 +389',
    value: '+389',
  },
  {
    code: 'MG',
    dial_code: '+261',
    flag: '🇲🇬',
    name: 'Madagascar',
    label: '🇲🇬 +261',
    value: '+261',
  },
  {
    code: 'MW',
    dial_code: '+265',
    flag: '🇲🇼',
    name: 'Malawi',
    label: '🇲🇼 +265',
    value: '+265',
  },
  {
    code: 'MY',
    dial_code: '+60',
    flag: '🇲🇾',
    name: 'Malaysia',
    label: '🇲🇾 +60',
    value: '+60',
  },
  {
    code: 'MV',
    dial_code: '+960',
    flag: '🇲🇻',
    name: 'Maldives',
    label: '🇲🇻 +960',
    value: '+960',
  },
  {
    code: 'ML',
    dial_code: '+223',
    flag: '🇲🇱',
    name: 'Mali',
    label: '🇲🇱 +223',
    value: '+223',
  },
  {
    code: 'MT',
    dial_code: '+356',
    flag: '🇲🇹',
    name: 'Malta',
    label: '🇲🇹 +356',
    value: '+356',
  },
  {
    code: 'MH',
    dial_code: '+692',
    flag: '🇲🇭',
    name: 'Marshall Islands',
    label: '🇲🇭 +692',
    value: '+692',
  },
  {
    code: 'MQ',
    dial_code: '+596',
    flag: '🇲🇶',
    name: 'Martinique',
    label: '🇲🇶 +596',
    value: '+596',
  },
  {
    code: 'MR',
    dial_code: '+222',
    flag: '🇲🇷',
    name: 'Mauritania',
    label: '🇲🇷 +222',
    value: '+222',
  },
  {
    code: 'MU',
    dial_code: '+230',
    flag: '🇲🇺',
    name: 'Mauritius',
    label: '🇲🇺 +230',
    value: '+230',
  },
  {
    code: 'YT',
    dial_code: '+262',
    flag: '🇾🇹',
    name: 'Mayotte',
    label: '🇾🇹 +262',
    value: '+262',
  },
  {
    code: 'MX',
    dial_code: '+52',
    flag: '🇲🇽',
    name: 'Mexico',
    label: '🇲🇽 +52',
    value: '+52',
  },
  {
    code: 'FM',
    dial_code: '+691',
    flag: '🇫🇲',
    name: 'Micronesia, Federated States of Micronesia',
    label: '🇫🇲 +691',
    value: '+691',
  },
  {
    code: 'MD',
    dial_code: '+373',
    flag: '🇲🇩',
    name: 'Moldova',
    label: '🇲🇩 +373',
    value: '+373',
  },
  {
    code: 'MC',
    dial_code: '+377',
    flag: '🇲🇨',
    name: 'Monaco',
    label: '🇲🇨 +377',
    value: '+377',
  },
  {
    code: 'MN',
    dial_code: '+976',
    flag: '🇲🇳',
    name: 'Mongolia',
    label: '🇲🇳 +976',
    value: '+976',
  },
  {
    code: 'ME',
    dial_code: '+382',
    flag: '🇲🇪',
    name: 'Montenegro',
    label: '🇲🇪 +382',
    value: '+382',
  },
  {
    code: 'MS',
    dial_code: '+1664',
    flag: '🇲🇸',
    name: 'Montserrat',
    label: '🇲🇸 +1664',
    value: '+1664',
  },
  {
    code: 'MA',
    dial_code: '+212',
    flag: '🇲🇦',
    name: 'Morocco',
    label: '🇲🇦 +212',
    value: '+212',
  },
  {
    code: 'MZ',
    dial_code: '+258',
    flag: '🇲🇿',
    name: 'Mozambique',
    label: '🇲🇿 +258',
    value: '+258',
  },
  {
    code: 'MM',
    dial_code: '+95',
    flag: '🇲🇲',
    name: 'Myanmar',
    label: '🇲🇲 +95',
    value: '+95',
  },
  {
    code: 'NA',
    dial_code: '+264',
    flag: '🇳🇦',
    name: 'Namibia',
    label: '🇳🇦 +264',
    value: '+264',
  },
  {
    code: 'NR',
    dial_code: '+674',
    flag: '🇳🇷',
    name: 'Nauru',
    label: '🇳🇷 +674',
    value: '+674',
  },
  {
    code: 'NP',
    dial_code: '+977',
    flag: '🇳🇵',
    name: 'Nepal',
    label: '🇳🇵 +977',
    value: '+977',
  },
  {
    code: 'NL',
    dial_code: '+31',
    flag: '🇳🇱',
    name: 'Netherlands',
    label: '🇳🇱 +31',
    value: '+31',
  },
  {
    code: 'AN',
    dial_code: '+599',
    flag: '🇳🇱',
    name: 'Netherlands Antilles',
    label: '🇳🇱 +599',
    value: '+599',
  },
  {
    code: 'NC',
    dial_code: '+687',
    flag: '🇳🇨',
    name: 'New Caledonia',
    label: '🇳🇨 +687',
    value: '+687',
  },
  {
    code: 'NZ',
    dial_code: '+64',
    flag: '🇳🇿',
    name: 'New Zealand',
    label: '🇳🇿 +64',
    value: '+64',
  },
  {
    code: 'NI',
    dial_code: '+505',
    flag: '🇳🇮',
    name: 'Nicaragua',
    label: '🇳🇮 +505',
    value: '+505',
  },
  {
    code: 'NE',
    dial_code: '+227',
    flag: '🇳🇪',
    name: 'Niger',
    label: '🇳🇪 +227',
    value: '+227',
  },
  {
    code: 'NG',
    dial_code: '+234',
    flag: '🇳🇬',
    name: 'Nigeria',
    label: '🇳🇬 +234',
    value: '+234',
  },
  {
    code: 'NU',
    dial_code: '+683',
    flag: '🇳🇺',
    name: 'Niue',
    label: '🇳🇺 +683',
    value: '+683',
  },
  {
    code: 'NF',
    dial_code: '+672',
    flag: '🇳🇫',
    name: 'Norfolk Island',
    label: '🇳🇫 +672',
    value: '+672',
  },
  {
    code: 'MP',
    dial_code: '+1670',
    flag: '🏳',
    name: 'Northern Mariana Islands',
    label: '🏳 +1670',
    value: '+1670',
  },
  {
    code: 'NO',
    dial_code: '+47',
    flag: '🇳🇴',
    name: 'Norway',
    label: '🇳🇴 +47',
    value: '+47',
  },
  {
    code: 'OM',
    dial_code: '+968',
    flag: '🇴🇲',
    name: 'Oman',
    label: '🇴🇲 +968',
    value: '+968',
  },
  {
    code: 'PK',
    dial_code: '+92',
    flag: '🇵🇰',
    name: 'Pakistan',
    label: '🇵🇰 +92',
    value: '+92',
  },
  {
    code: 'PW',
    dial_code: '+680',
    flag: '🇵🇼',
    name: 'Palau',
    label: '🇵🇼 +680',
    value: '+680',
  },
  {
    code: 'PS',
    dial_code: '+970',
    flag: '🇵🇸',
    name: 'Palestinian Territory, Occupied',
    label: '🇵🇸 +970',
    value: '+970',
  },
  {
    code: 'PA',
    dial_code: '+507',
    flag: '🇵🇦',
    name: 'Panama',
    label: '🇵🇦 +507',
    value: '+507',
  },
  {
    code: 'PG',
    dial_code: '+675',
    flag: '🇵🇬',
    name: 'Papua New Guinea',
    label: '🇵🇬 +675',
    value: '+675',
  },
  {
    code: 'PY',
    dial_code: '+595',
    flag: '🇵🇾',
    name: 'Paraguay',
    label: '🇵🇾 +595',
    value: '+595',
  },
  {
    code: 'PE',
    dial_code: '+51',
    flag: '🇵🇪',
    name: 'Peru',
    label: '🇵🇪 +51',
    value: '+51',
  },
  {
    code: 'PH',
    dial_code: '+63',
    flag: '🇵🇭',
    name: 'Philippines',
    label: '🇵🇭 +63',
    value: '+63',
  },
  {
    code: 'PN',
    dial_code: '+64',
    flag: '🇵🇳',
    name: 'Pitcairn',
    label: '🇵🇳 +64',
    value: '+64',
  },
  {
    code: 'PL',
    dial_code: '+48',
    flag: '🇵🇱',
    name: 'Poland',
    label: '🇵🇱 +48',
    value: '+48',
  },
  {
    code: 'PT',
    dial_code: '+351',
    flag: '🇵🇹',
    name: 'Portugal',
    label: '🇵🇹 +351',
    value: '+351',
  },
  {
    code: 'PR',
    dial_code: '+1939',
    flag: '🇵🇷',
    name: 'Puerto Rico',
    label: '🇵🇷 +1939',
    value: '+1939',
  },
  {
    code: 'QA',
    dial_code: '+974',
    flag: '🇶🇦',
    name: 'Qatar',
    label: '🇶🇦 +974',
    value: '+974',
  },
  {
    code: 'RO',
    dial_code: '+40',
    flag: '🇷🇴',
    name: 'Romania',
    label: '🇷🇴 +40',
    value: '+40',
  },
  {
    code: 'RU',
    dial_code: '+7',
    flag: '🇷🇺',
    name: 'Russia',
    label: '🇷🇺 +7',
    value: '+7',
  },
  {
    code: 'RW',
    dial_code: '+250',
    flag: '🇷🇼',
    name: 'Rwanda',
    label: '🇷🇼 +250',
    value: '+250',
  },
  {
    code: 'RE',
    dial_code: '+262',
    flag: '🇫🇷',
    name: 'Reunion',
    label: '🇫🇷 +262',
    value: '+262',
  },
  {
    code: 'BL',
    dial_code: '+590',
    flag: '🇧🇱',
    name: 'Saint Barthelemy',
    label: '🇧🇱 +590',
    value: '+590',
  },
  {
    code: 'SH',
    dial_code: '+290',
    flag: '🇸🇭',
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    label: '🇸🇭 +290',
    value: '+290',
  },
  {
    code: 'KN',
    dial_code: '+1869',
    flag: '�🇳',
    name: 'Saint Kitts and Nevis',
    label: '�🇳 +1869',
    value: '+1869',
  },
  {
    code: 'LC',
    dial_code: '+1758',
    flag: '🇱🇨',
    name: 'Saint Lucia',
    label: '🇱🇨 +1758',
    value: '+1758',
  },
  {
    code: 'MF',
    dial_code: '+590',
    flag: '🏳',
    name: 'Saint Martin',
    label: '🏳 +590',
    value: '+590',
  },
  {
    code: 'PM',
    dial_code: '+508',
    flag: '🇵🇲',
    name: 'Saint Pierre and Miquelon',
    label: '🇵🇲 +508',
    value: '+508',
  },
  {
    code: 'VC',
    dial_code: '+1784',
    flag: '🇻🇨',
    name: 'Saint Vincent and the Grenadines',
    label: '🇻🇨 +1784',
    value: '+1784',
  },
  {
    code: 'WS',
    dial_code: '+685',
    flag: '🇼🇸',
    name: 'Samoa',
    label: '🇼🇸 +685',
    value: '+685',
  },
  {
    code: 'SM',
    dial_code: '+378',
    flag: '🇸🇲',
    name: 'San Marino',
    label: '🇸🇲 +378',
    value: '+378',
  },
  {
    code: 'ST',
    dial_code: '+239',
    flag: '🇸🇹',
    name: 'Sao Tome and Principe',
    label: '🇸🇹 +239',
    value: '+239',
  },
  {
    code: 'SA',
    dial_code: '+966',
    flag: '🇸🇦',
    name: 'Saudi Arabia',
    label: '🇸🇦 +966',
    value: '+966',
  },
  {
    code: 'SN',
    dial_code: '+221',
    flag: '🇸🇳',
    name: 'Senegal',
    label: '🇸🇳 +221',
    value: '+221',
  },
  {
    code: 'RS',
    dial_code: '+381',
    flag: '🇷🇸',
    name: 'Serbia',
    label: '🇷🇸 +381',
    value: '+381',
  },
  {
    code: 'SC',
    dial_code: '+248',
    flag: '🇸🇨',
    name: 'Seychelles',
    label: '🇸🇨 +248',
    value: '+248',
  },
  {
    code: 'SL',
    dial_code: '+232',
    flag: '🇸🇱',
    name: 'Sierra Leone',
    label: '🇸🇱 +232',
    value: '+232',
  },
  {
    code: 'SG',
    dial_code: '+65',
    flag: '🇸🇬',
    name: 'Singapore',
    label: '🇸🇬 +65',
    value: '+65',
  },
  {
    code: 'SK',
    dial_code: '+421',
    flag: '🇸🇰',
    name: 'Slovakia',
    label: '🇸🇰 +421',
    value: '+421',
  },
  {
    code: 'SI',
    dial_code: '+386',
    flag: '🇸🇮',
    name: 'Slovenia',
    label: '🇸🇮 +386',
    value: '+386',
  },
  {
    code: 'SB',
    dial_code: '+677',
    flag: '🇸🇧',
    name: 'Solomon Islands',
    label: '🇸🇧 +677',
    value: '+677',
  },
  {
    code: 'SO',
    dial_code: '+252',
    flag: '🇸🇴',
    name: 'Somalia',
    label: '🇸🇴 +252',
    value: '+252',
  },
  {
    code: 'ZA',
    dial_code: '+27',
    flag: '🇿🇦',
    name: 'South Africa',
    label: '🇿🇦 +27',
    value: '+27',
  },
  {
    code: 'SS',
    dial_code: '+211',
    flag: '🇸🇸',
    name: 'South Sudan',
    label: '🇸🇸 +211',
    value: '+211',
  },
  {
    code: 'GS',
    dial_code: '+500',
    flag: '🇬🇸',
    name: 'South Georgia and the South Sandwich Islands',
    label: '🇬🇸 +500',
    value: '+500',
  },
  {
    code: 'ES',
    dial_code: '+34',
    flag: '🇪🇸',
    name: 'Spain',
    label: '🇪🇸 +34',
    value: '+34',
  },
  {
    code: 'LK',
    dial_code: '+94',
    flag: '🇱🇰',
    name: 'Sri Lanka',
    label: '🇱🇰 +94',
    value: '+94',
  },
  {
    code: 'SD',
    dial_code: '+249',
    flag: '🇸🇩',
    name: 'Sudan',
    label: '🇸🇩 +249',
    value: '+249',
  },
  {
    code: 'SR',
    dial_code: '+597',
    flag: '🇸🇷',
    name: 'Suriname',
    label: '🇸🇷 +597',
    value: '+597',
  },
  {
    code: 'SJ',
    dial_code: '+47',
    flag: '🇩🇰',
    name: 'Svalbard and Jan Mayen',
    label: '🇩🇰 +47',
    value: '+47',
  },
  {
    code: 'SZ',
    dial_code: '+268',
    flag: '🇸🇿',
    name: 'Swaziland',
    label: '🇸🇿 +268',
    value: '+268',
  },
  {
    code: 'SE',
    dial_code: '+46',
    flag: '🇸🇪',
    name: 'Sweden',
    label: '🇸🇪 +46',
    value: '+46',
  },
  {
    code: 'CH',
    dial_code: '+41',
    flag: '🇨🇭',
    name: 'Switzerland',
    label: '🇨🇭 +41',
    value: '+41',
  },
  {
    code: 'SY',
    dial_code: '+963',
    flag: '🇸🇾',
    name: 'Syrian Arab Republic',
    label: '🇸🇾 +963',
    value: '+963',
  },
  {
    code: 'TW',
    dial_code: '+886',
    flag: '🇹🇼',
    name: 'Taiwan',
    label: '🇹🇼 +886',
    value: '+886',
  },
  {
    code: 'TJ',
    dial_code: '+992',
    flag: '🇹🇯',
    name: 'Tajikistan',
    label: '🇹🇯 +992',
    value: '+992',
  },
  {
    code: 'TZ',
    dial_code: '+255',
    flag: '🇹🇿',
    name: 'Tanzania, United Republic of Tanzania',
    label: '🇹🇿 +255',
    value: '+255',
  },
  {
    code: 'TH',
    dial_code: '+66',
    flag: '🇹🇭',
    name: 'Thailand',
    label: '🇹🇭 +66',
    value: '+66',
  },
  {
    code: 'TL',
    dial_code: '+670',
    flag: '🇹🇱',
    name: 'Timor-Leste',
    label: '🇹🇱 +670',
    value: '+670',
  },
  {
    code: 'TG',
    dial_code: '+228',
    flag: '🇹🇬',
    name: 'Togo',
    label: '🇹🇬 +228',
    value: '+228',
  },
  {
    code: 'TK',
    dial_code: '+690',
    flag: '🇹🇰',
    name: 'Tokelau',
    label: '🇹🇰 +690',
    value: '+690',
  },
  {
    code: 'TO',
    dial_code: '+676',
    flag: '🇹🇴',
    name: 'Tonga',
    label: '🇹🇴 +676',
    value: '+676',
  },
  {
    code: 'TT',
    dial_code: '+1868',
    flag: '🇹🇹',
    name: 'Trinidad and Tobago',
    label: '🇹🇹 +1868',
    value: '+1868',
  },
  {
    code: 'TN',
    dial_code: '+216',
    flag: '🇹🇳',
    name: 'Tunisia',
    label: '🇹🇳 +216',
    value: '+216',
  },
  {
    code: 'TR',
    dial_code: '+90',
    flag: '🇹🇷',
    name: 'Turkey',
    label: '🇹🇷 +90',
    value: '+90',
  },
  {
    code: 'TM',
    dial_code: '+993',
    flag: '🇹🇲',
    name: 'Turkmenistan',
    label: '🇹🇲 +993',
    value: '+993',
  },
  {
    code: 'TC',
    dial_code: '+1649',
    flag: '🇹🇨',
    name: 'Turks and Caicos Islands',
    label: '🇹🇨 +1649',
    value: '+1649',
  },
  {
    code: 'TV',
    dial_code: '+688',
    flag: '🇹🇻',
    name: 'Tuvalu',
    label: '🇹🇻 +688',
    value: '+688',
  },
  {
    code: 'UG',
    dial_code: '+256',
    flag: '🇺🇬',
    name: 'Uganda',
    label: '🇺🇬 +256',
    value: '+256',
  },
  {
    code: 'UA',
    dial_code: '+380',
    flag: '🇺🇦',
    name: 'Ukraine',
    label: '🇺🇦 +380',
    value: '+380',
  },
  {
    code: 'AE',
    dial_code: '+971',
    flag: '🇦🇪',
    name: 'United Arab Emirates',
    label: '🇦🇪 +971',
    value: '+971',
  },
  {
    code: 'GB',
    dial_code: '+44',
    flag: '🇬🇧',
    name: 'United Kingdom',
    label: '🇬🇧 +44',
    value: '+44',
  },
  {
    code: 'US',
    dial_code: '+1',
    flag: '🇺🇸',
    name: 'United States',
    label: '🇺🇸 +1',
    value: '+1',
  },
  {
    code: 'UY',
    dial_code: '+598',
    flag: '🇺🇾',
    name: 'Uruguay',
    label: '🇺🇾 +598',
    value: '+598',
  },
  {
    code: 'UZ',
    dial_code: '+998',
    flag: '🇺🇿',
    name: 'Uzbekistan',
    label: '🇺🇿 +998',
    value: '+998',
  },
  {
    code: 'VU',
    dial_code: '+678',
    flag: '🇻🇺',
    name: 'Vanuatu',
    label: '🇻🇺 +678',
    value: '+678',
  },
  {
    code: 'VE',
    dial_code: '+58',
    flag: '🇻🇪',
    name: 'Venezuela, Bolivarian Republic of Venezuela',
    label: '🇻🇪 +58',
    value: '+58',
  },
  {
    code: 'VN',
    dial_code: '+84',
    flag: '🇻🇳',
    name: 'Vietnam',
    label: '🇻🇳 +84',
    value: '+84',
  },
  {
    code: 'VG',
    dial_code: '+1284',
    flag: '🇻🇬',
    name: 'Virgin Islands, British',
    label: '🇻🇬 +1284',
    value: '+1284',
  },
  {
    code: 'VI',
    dial_code: '+1340',
    flag: '🇻🇮',
    name: 'Virgin Islands, U.S.',
    label: '🇻🇮 +1340',
    value: '+1340',
  },
  {
    code: 'WF',
    dial_code: '+681',
    flag: '🇼🇫',
    name: 'Wallis and Futuna',
    label: '🇼🇫 +681',
    value: '+681',
  },
  {
    code: 'YE',
    dial_code: '+967',
    flag: '🇾🇪',
    name: 'Yemen',
    label: '🇾🇪 +967',
    value: '+967',
  },
  {
    code: 'ZM',
    dial_code: '+260',
    flag: '🇿🇲',
    name: 'Zambia',
    label: '🇿🇲 +260',
    value: '+260',
  },
  {
    code: 'ZW',
    dial_code: '+263',
    flag: '🇿🇼',
    name: 'Zimbabwe',
    label: '🇿🇼 +263',
    value: '+263',
  },
];

export default countries;
